# -*- coding: utf-8 -*-
"""privateSedScript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkjtuAp03UXXw2oAyGFU1y7VwjOO2Ltg
"""

import os
import json
import stat

overall = {
    "data": []
}

data = [];

os.system("rm TestCase1/out.c")
#------------------------------test case 1---------------------------
msg = "Correct output."
total = 1
result = {
      "testid": "1",
      "status": "success",
      "score": 0,
      "maximum marks" : 1,
      "message": ""
    }

st = os.stat('./change_var.sh')
os.chmod('./change_var.sh', st.st_mode | stat.S_IEXEC)
os.system("./change_var.sh d dvar TestCase1/test1.c > TestCase1/out.c")
file1 = open('TestCase1/output1.c', 'r')
Lines1 = file1.readlines()
file2 = open('TestCase1/out.c', 'r')
Lines2 = file2.readlines()

if len(Lines1) < len(Lines2) :
    total = 0
    msg = "Wrong output, Your output genrates some extra lines"
elif len(Lines1) > len(Lines2) :
    total = 0
    msg = "Wrong output, Some statments are missing"
else :
    for i in range(len(Lines1)) :
        if Lines1[i].strip() != Lines2[i].strip() :
            total = 0
            msg = "Wrong output, Expected statment : '" + Lines1[i].strip() + "' Your output : '" + Lines2[i].strip() + "'"
            break
    
result["testid"] = 1
result["score"] = total
result["message"] = msg

data.append(result)
os.system("rm TestCase1/out.c")

#------------------------------test case 2---------------------------
msg = "Correct output."
total = 1
result = {
      "testid": "1",
      "status": "success",
      "score": 0,
      "maximum marks" : 1,
      "message": ""
    }

os.system("./change_var.sh n1 number TestCase2/test2.c > TestCase2/out.c")
file1 = open('TestCase2/output2.c', 'r')
Lines1 = file1.readlines()
file2 = open('TestCase2/out.c', 'r')
Lines2 = file2.readlines()

if len(Lines1) < len(Lines2) :
    total = 0
    msg = "Wrong output, Your output genrates some extra lines"
elif len(Lines1) > len(Lines2) :
    total = 0
    msg = "Wrong output, Some statments are missing"
else :
    for i in range(len(Lines1)) :
        if Lines1[i].strip() != Lines2[i].strip() :
            total = 0
            msg = "Wrong output, Expected statment : '" + Lines1[i].strip() + "' Your output : '" + Lines2[i].strip() + "'"
            break
    
result["testid"] = 2
result["score"] = total
result["message"] = msg

data.append(result)
os.system("rm TestCase2/out.c")

#------------------------------test case 3---------------------------
msg = "Correct output."
total = 1
result = {
      "testid": "1",
      "status": "success",
      "score": 0,
      "maximum marks" : 1,
      "message": ""
    }

os.system("./change_var.sh a aaa TestCase3/test3.c > TestCase3/out.c")
file1 = open('TestCase3/output3.c', 'r')
Lines1 = file1.readlines()
file2 = open('TestCase3/out.c', 'r')
Lines2 = file2.readlines()

if len(Lines1) < len(Lines2) :
    total = 0
    msg = "Wrong output, Your output genrates some extra lines"
elif len(Lines1) > len(Lines2) :
    total = 0
    msg = "Wrong output, Some statments are missing"
else :
    for i in range(len(Lines1)) :
        if Lines1[i].strip() != Lines2[i].strip() :
            total = 0
            msg = "Wrong output, Expected statment : '" + Lines1[i].strip() + "' Your output : '" + Lines2[i].strip() + "'"
            break
    
result["testid"] = 3
result["score"] = total
result["message"] = msg

data.append(result)
os.system("rm TestCase3/out.c")

#------------------------------test case 4---------------------------
msg = "Correct output."
total = 1
result = {
      "testid": "1",
      "status": "success",
      "score": 0,
      "maximum marks" : 1,
      "message": ""
    }

os.system("./change_var.sh number1 num1 TestCase4/test4.c > TestCase4/out.c")
file1 = open('TestCase4/output4.c', 'r')
Lines1 = file1.readlines()
file2 = open('TestCase4/out.c', 'r')
Lines2 = file2.readlines()

if len(Lines1) < len(Lines2) :
    total = 0
    msg = "Wrong output, Your output genrates some extra lines"
elif len(Lines1) > len(Lines2) :
    total = 0
    msg = "Wrong output, Some statments are missing"
else :
    for i in range(len(Lines1)) :
        if Lines1[i].strip() != Lines2[i].strip() :
            total = 0
            msg = "Wrong output, Expected statment : '" + Lines1[i].strip() + "' Your output : '" + Lines2[i].strip() + "'"
            break
    
result["testid"] = 4
result["score"] = total
result["message"] = msg

data.append(result)
os.system("rm TestCase4/out.c")

#------------------------------test case 5---------------------------
msg = "Correct output."
total = 1
result = {
      "testid": "1",
      "status": "success",
      "score": 0,
      "maximum marks" : 1,
      "message": ""
    }

os.system("./change_var.sh number1 num1 TestCase5/test5.c > TestCase5/out.c")
file1 = open('TestCase5/output5.c', 'r')
Lines1 = file1.readlines()
file2 = open('TestCase5/out.c', 'r')
Lines2 = file2.readlines()

if len(Lines1) < len(Lines2) :
    total = 0
    msg = "Wrong output, Your output genrates some extra lines"
elif len(Lines1) > len(Lines2) :
    total = 0
    msg = "Wrong output, Some statments are missing"
else :
    for i in range(len(Lines1)) :
        if Lines1[i].strip() != Lines2[i].strip() :
            total = 0
            msg = "Wrong output, Expected statment : '" + Lines1[i].strip() + "' Your output : '" + Lines2[i].strip() + "'"
            break
    
result["testid"] = 5
result["score"] = total
result["message"] = msg

data.append(result)
os.system("rm TestCase5/out.c")




overall['data'] = data
print(json.dumps(overall, indent=4))
with open('../evaluate.json', 'w') as f:
    json.dump(overall,f,indent=4)

